### ISSUE TITLE
Incorrect conversion to metric

### ISSUE THREAD

**Issue by clivensperger** [scoyoc/climateAnalyzeR#3]
Using the 'convert = TRUE' option with import_data( ), some of the metric values in the resulting data frame are incorrect. This appears to be the case for the columns tmax_cy_c, tmax_wy_c, tmin_cy_c, and tmin_cy_c. The precip columns (prcp_cy_mm and prcp_wy_mm) are correct.

**Comment by scoyoc** [comment]
Resolved. Parentheses were added to the internal equation used to calculate C from F. Testing indicates that the problem is resolved. Please let me know if you find this error is still occurring.
